services:
  - type: web
    name: youtube-combine
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/health/keep-active
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: API_KEYS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REACT_APP_SERVER_URL
        value: "/api"
