-- Prerequisite: `comments` table exists with migration 004 applied (updated_at present).
-- Lets YouTube-imported comments live in the same `comments` table as native
-- ones: user_id becomes nullable (NULL for youtube-sourced rows, since those
-- authors aren't rows in `channels`), plus source, external_id (YouTube's
-- own comment id, unique), author_name/author_avatar, and like_count.
ALTER TABLE comments MODIFY user_id VARCHAR(32) NULL

DROP PROCEDURE IF EXISTS add_youtube_comment_cols
CREATE PROCEDURE add_youtube_comment_cols() BEGIN IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND COLUMN_NAME = 'source') THEN ALTER TABLE comments ADD COLUMN source ENUM('native', 'youtube') NOT NULL DEFAULT 'native' AFTER user_id; END IF; IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND COLUMN_NAME = 'external_id') THEN ALTER TABLE comments ADD COLUMN external_id VARCHAR(64) NULL AFTER source; END IF; IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND COLUMN_NAME = 'author_name') THEN ALTER TABLE comments ADD COLUMN author_name VARCHAR(255) NULL AFTER external_id; END IF; IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND COLUMN_NAME = 'author_avatar') THEN ALTER TABLE comments ADD COLUMN author_avatar VARCHAR(512) NULL DEFAULT '' AFTER author_name; END IF; IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND COLUMN_NAME = 'like_count') THEN ALTER TABLE comments ADD COLUMN like_count INT NOT NULL DEFAULT 0 AFTER author_avatar; END IF; IF NOT EXISTS (SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'comments' AND INDEX_NAME = 'uniq_comment_external_id') THEN ALTER TABLE comments ADD UNIQUE KEY uniq_comment_external_id (external_id); END IF; END
CALL add_youtube_comment_cols()
DROP PROCEDURE add_youtube_comment_cols